services:
  ontop:
    image: ontop/ontop
    environment:
#      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/foaf.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/obda/artemis.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/duckdb.properties
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
      ONTOP_LAZY_INIT: "true"
    volumes:
      - ./input:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
      - /home/shared/obda:/opt/ontop/obda
    ports:
      - "8080:8080"
